#ifndef IN_GAME_PROPOBJ_H
#define IN_GAME_PROPOBJ_H
#include <ultra64.h>
#include "data.h"
#include "types.h"

extern u32 var800698f0;
extern u32 var800698f4;
extern struct prop *g_EmbedProp;
extern s32 g_EmbedHitPart;
extern f32 g_CctvWaitScale;
extern f32 g_CctvDamageRxScale;
extern f32 g_AutogunAccuracyScale;
extern f32 g_AutogunDamageTxScale;
extern f32 g_AutogunDamageRxScale;
extern struct beam *g_ThrownLaptopBeams;

void alarm_activate(void);
void alarm_deactivate(void);
bool alarm_is_active(void);
f32 countdown_timer_get_value60(void);
bool countdown_timer_is_visible(void);
bool countdown_timer_is_running(void);
void countdown_timer_set_running(bool running);
void countdown_timer_set_value60(f32 value);
void countdown_timer_set_visible(u32 reason, bool visible);
void countdown_timer_tick(void);
bool door_call_lift(struct prop *doorprop, bool allowclose);
bool door_is_padlock_free(struct doorobj *door);
bool obj_can_pickup_from_safe(struct defaultobj *obj);
void obj_update_linked_scenery(struct defaultobj *obj, struct prop *prop);
f32 obj_get_local_x_min(struct modelrodata_bbox *bbox);
f32 obj_get_local_x_max(struct modelrodata_bbox *bbox);
f32 obj_get_local_y_min(struct modelrodata_bbox *bbox);
f32 obj_get_local_y_max(struct modelrodata_bbox *bbox);
f32 obj_get_local_z_min(struct modelrodata_bbox *bbox);
f32 obj_get_local_z_max(struct modelrodata_bbox *bbox);
f32 obj_get_rotated_local_x_min_by_mtx4(struct modelrodata_bbox *bbox, Mtxf *mtx);
f32 obj_get_rotated_local_x_max_by_mtx4(struct modelrodata_bbox *bbox, Mtxf *mtx);
f32 obj_get_rotated_local_y_min_by_mtx4(struct modelrodata_bbox *bbox, Mtxf *mtx);
f32 obj_get_rotated_local_y_max_by_mtx4(struct modelrodata_bbox *bbox, Mtxf *mtx);
f32 obj_get_rotated_local_z_min_by_mtx4(struct modelrodata_bbox *bbox, Mtxf *mtx);
f32 obj_get_rotated_local_z_max_by_mtx4(struct modelrodata_bbox *bbox, Mtxf *mtx);
f32 obj_get_rotated_local_x_min_by_mtx3(struct modelrodata_bbox *bbox, f32 realrot[3][3]);
f32 obj_get_rotated_local_x_max_by_mtx3(struct modelrodata_bbox *bbox, f32 realrot[3][3]);
f32 obj_get_rotated_local_y_min_by_mtx3(struct modelrodata_bbox *bbox, f32 realrot[3][3]);
f32 obj_get_rotated_local_y_max_by_mtx3(struct modelrodata_bbox *bbox, f32 realrot[3][3]);
f32 obj_get_rotated_local_z_min_by_mtx3(struct modelrodata_bbox *bbox, f32 realrot[3][3]);
f32 obj_get_rotated_local_z_max_by_mtx3(struct modelrodata_bbox *bbox, f32 realrot[3][3]);
f32 obj_get_rotated_local_min(struct modelrodata_bbox *bbox, f32 arg1, f32 arg2, f32 arg3);
f32 obj_get_rotated_local_max(struct modelrodata_bbox *bbox, f32 arg1, f32 arg2, f32 arg3);
s32 obj_calculate_geo_block_vertices(f32 xmin, f32 xmax, f32 ymin, f32 ymax, f32 zmin, f32 zmax, Mtxf *mtx, struct geoblock *block);
void obj_calculate_geo_block_from_bbox_and_mtx(struct modelrodata_bbox *bbox, Mtxf *mtx, struct geoblock *block);
void obj_calculate_geo_block_from_node19_data(struct modelrodata_type19 *rodata19, struct modelrodata_bbox *bbox, Mtxf *mtx, struct geoblock *block);
bool func0f0675c8(struct coord *pos, f32 arg1, struct modelrodata_bbox *bbox, Mtxf *mtx);
bool func0f0677ac(struct coord *coord, struct coord *arg1, struct coord *pos, struct coord *normal, struct coord *up, struct coord *look, f32 xmin, f32 xmax, f32 ymin, f32 ymax, f32 zmin, f32 zmax);
bool func0f0678f8(struct coord *coord, struct coord *arg1, s32 padnum);
bool func0f06797c(struct coord *coord, f32 arg1, s32 padnum);
bool func0f0679ac(struct model *model, f32 *max, f32 *min, f32 arg3[2], f32 arg4[2]);
void model_get_screen_coords_by_axis(struct model *model, f32 *max, f32 *min, s32 axis);
void model_get_screen_coords3(struct model *model, f32 *xmax, f32 *xmin, f32 *ymax, f32 *ymin);
bool model_get_screen_coords2(struct model *model, f32 *x2, f32 *x1, f32 *y2, f32 *y1);
bool model_get_screen_coords(struct model *model, f32 *x2, f32 *x1, f32 *y2, f32 *y1);
void func0f06803c(struct coord *arg0, f32 *arg1, f32 *arg2, f32 *arg3, f32 *arg4);
struct defaultobj *obj_find_by_pad_num(s32 padnum);
struct defaultobj *obj_find_by_pos(struct coord *pos, RoomNum *rooms);
void projectile_free(struct projectile *projectile);
void projectiles_unref_owner(struct prop *owner);
void projectile_reset(struct projectile *projectile);
struct projectile *projectile_allocate(void);
void func0f0685e4(struct prop *prop);
void projectile_set_sticky(struct prop *prop);
void embedment_free(struct embedment *embedment);
struct embedment *embedment_allocate(void);
s32 obj_get_shots_taken(struct defaultobj *obj);
s32 obj_get_destroyed_level(struct defaultobj *obj);
struct modelnode *func0f0687e4(struct model *model);
struct modelnode *modeldef_find_bbox_node(struct modeldef *modeldef);
struct modelrodata_bbox *modeldef_find_bbox_rodata(struct modeldef *modeldef);
struct modelnode *model_find_bbox_node(struct model *model);
struct modelrodata_bbox *model_find_bbox_rodata(struct model *model);
struct modelnode *obj_find_bbox_node(struct defaultobj *obj);
struct modelrodata_bbox *obj_find_bbox_rodata(struct defaultobj *obj);
s32 obj_get_average_brightness_in_rooms(RoomNum *rooms, s32 arg1);
s32 door0f068c04(struct prop *prop, s32 *arg1, s32 *arg2);
s32 func0f068fc8(struct prop *prop, bool arg1);
void prop_calculate_shade_colour(struct prop *prop, u8 *nextcol, u16 floorcol);
void prop_calculate_shade_info(struct prop *prop, u8 *nextcol, u16 floorcol);
void colour_tween(u8 *col, u8 *nextcol);
void obj_merge_colour_fracs(s32 *colour, s32 shademode, f32 fracs[4]);
void func0f069850(struct defaultobj *obj, struct coord *pos, f32 rot[3][3], struct geocyl *cyl);
void func0f069b4c(struct defaultobj *obj);
void func0f069c1c(struct defaultobj *obj);
void func0f069c70(struct defaultobj *obj, bool arg1, bool arg2);
void obj_init_toggle_nodes(struct defaultobj *obj);
void obj_create_one_debris(struct defaultobj *obj, s32 partindex, struct prop *prop);
void obj_create_debris(struct defaultobj *obj, struct prop *prop);
struct prop *obj_init(struct defaultobj *obj, struct modeldef *modeldef, struct prop *prop, struct model *model);
struct prop *obj_init_with_model_def(struct defaultobj *obj, struct modeldef *modeldef);
struct prop *obj_init_with_auto_model(struct defaultobj *obj);
void func0f06a580(struct defaultobj *obj, struct coord *pos, Mtxf *matrix, RoomNum *rooms);
f32 func0f06a620(struct defaultobj *obj);
void func0f06a730(struct defaultobj *obj, struct coord *arg1, Mtxf *matrix, RoomNum *rooms, struct coord *arg4);
void func0f06ab60(struct defaultobj *obj, struct coord *arg1, Mtxf *matrix, RoomNum *rooms, struct coord *arg4);
void obj_free_projectile(struct defaultobj *obj);
void obj_free_embedment_or_projectile(struct prop *prop);
void obj_free(struct defaultobj *obj, bool freeprop, bool canregen);
void obj_free_permanently(struct defaultobj *obj, bool freeprop);
f32 obj_get_radius(struct defaultobj *obj);
bool func0f06b39c(struct coord *pos, struct coord *dir, struct coord *aimpos, f32 arg3);
bool func0f06b488(struct prop *prop, struct coord *arg1, struct coord *arg2, struct coord *arg3, struct coord *arg4, struct coord *arg5, f32 *arg6);
bool func0f06b610(struct defaultobj *obj, struct coord *arg1, struct coord *arg2, struct coord *arg3, f32 arg4, struct coord *arg5, struct coord *arg6, struct coord *arg7, struct coord *arg8, f32 *arg9);
bool func0f06bea0(struct model *model, struct modelnode *arg1, struct modelnode *arg2, struct coord *arg3, struct coord *arg4, void *arg5, f32 *arg6, struct modelnode **arg7, s32 *hitpart, s32 *arg9, struct modelnode **arg10);
bool func0f06c28c(struct chrdata *chr, struct coord *arg1, struct coord *arg2, struct coord *arg3, f32 arg4, struct coord *arg5, struct coord *arg6, struct coord *arg7, struct coord *arg8, f32 *arg9);
bool projectile_find_colliding_prop(struct prop *prop, struct coord *pos, struct coord *arg2, u32 cdtypes, struct coord *arg4, struct coord *arg5, RoomNum *rooms);
s32 func0f06cd00(struct defaultobj *obj, struct coord *pos, struct coord *arg2, struct coord *arg3);
bool func0f06d37c(struct defaultobj *obj, struct coord *arg1, struct coord *arg2, struct coord *arg3);
void apply_speed(f32 *distdone, f32 maxdist, f32 *speed, f32 accel, f32 decel, f32 maxspeed);
void apply_rotation(f32 *angle, f32 maxrot, f32 *speed, f32 accel, f32 decel, f32 maxspeed);
void projectile_fall(struct defaultobj *obj, f32 mtx[3][3]);
void knife_play_woosh_sound(struct defaultobj *obj);
void func0f06e9cc(struct coord *arg0, Mtxf *arg1);
void obj_land2(struct defaultobj *obj, struct coord *arg1, struct coord *arg2);
void bolt_land(struct weaponobj *weapon, struct coord *arg1);
void knife_land(struct defaultobj *obj, struct coord *arg1, struct coord *arg2);
bool obj_embed(struct prop *prop, struct prop *parent, struct model *model, struct modelnode *node);
void obj_land(struct prop *prop, struct coord *arg1, struct coord *arg2, bool *embedded);
bool prop_explode(struct prop *prop, s32 explosiontype);
void ammocrate_tick(struct prop *ammocrate);
void weapon_tick(struct prop *weapon);
void func0f07063c(struct prop *prop, bool fulltick);
void obj_drop_recursively(struct prop *prop, bool arg1);
void func0f0706f8(struct prop *prop, bool fulltick);
void func0f07079c(struct prop *prop, bool fulltick);
s32 glass_calculate_opacity(struct coord *pos, f32 xludist, f32 opadist, f32 arg3);
void func0f070a1c(struct modelrodata_bbox *bbox, f32 realrot[3][3], struct coord *pos, struct coord *vertices);
void func0f070bd0(struct modelrodata_type19 *rodata, f32 realrot[3][3], struct coord *pos, struct coord *vertices);
void func0f070ca0(struct defaultobj *obj, struct geotilef *tile, u32 flags, struct modelrodata_bbox *bbox, struct modelrodata_type19 *rodata);
void lift_activate(struct prop *prop, u8 liftnum);
struct prop *lift_find_by_pad(s16 padnum);
f32 lift_get_y(struct liftobj *lift);
void lift_update_tiles(struct liftobj *lift, bool stationary);
void lift_go_to_stop(struct liftobj *lift, s32 stopnum);
f32 obj_get_hov_bob_offset_y(struct defaultobj *obj);
void hov_update_ground(struct defaultobj *obj, struct hov *hov, struct coord *pos, RoomNum *rooms, f32 matrix[3][3]);
void hov_tick(struct defaultobj *obj, struct hov *hov);
s32 obj_is_hoverprop_or_bike(struct defaultobj *obj);
f32 hoverprop_get_turn_angle(struct defaultobj *obj);
void hoverprop_set_turn_angle(struct defaultobj *obj, f32 angle);
s32 func0f072144(struct defaultobj *obj, struct coord *arg1, f32 arg2, bool arg3);
void hovercar_find_next_path(struct hovercarobj *hovercar);
void hovercar_start_next_path(struct hovercarobj *hovercar);
void hovercar_increment_step(struct hovercarobj *hovercar);
f32 obj_collide(struct defaultobj *obj, struct coord *arg1, f32 arg2);
void hoverbike_update_movement(struct hoverbikeobj *hoverbike, f32 arg1, f32 arg2, f32 arg3);
void platform_displace_props2(struct prop *platform, Mtxf *arg1);
bool rocket_tick_fbw(struct weaponobj *rocket);
s32 projectile_launch(struct defaultobj *obj, struct projectile *projectile, struct coord *arg2, struct coord *arg3);
s32 projectile_tick(struct defaultobj *obj, bool *embedded);
void door_tick(struct prop *doorprop);
void door_update_portal_if_windowed(struct prop *door, s32 playercount);
void door_init_matrices(struct prop *door);
void platform_displace_props(struct prop *platform, s16 *propnums, struct coord *prevpos, struct coord *newpos);
void lift_tick(struct prop *lift);
void escastep_tick(struct prop *escalator);
void cctv_tick(struct prop *camera);
void cctv_init_matrices(struct prop *cctv, Mtxf *mtx);
void fan_tick(struct prop *fan);
void fan_update_model(struct prop *fan);
void autogun_tick(struct prop *autogun);
void autogun_init_matrices(struct prop *autogun, Mtxf *mtx);
void autogun_tick_shoot(struct prop *autogun);
void chopper_init_matrices(struct prop *chopper);
struct chopperobj *chopper_from_hovercar(struct chopperobj *obj);
bool chopper_check_target_in_fov(struct chopperobj *hovercar, u8 param_2);
bool chopper_check_target_in_sight(struct chopperobj *obj);
void chopper_set_target(struct chopperobj *obj, u32 chrnum);
bool chopper_attack(struct chopperobj *obj);
bool chopper_stop(struct chopperobj *obj);
bool chopper_set_armed(struct chopperobj *obj, bool armed);
void chopper_restart_timer(struct chopperobj *obj);
f32 chopper_get_timer(struct chopperobj *heli);
void chopper_set_max_damage(struct chopperobj *obj, u16 health);
f32 func0f07b164(struct coord *pos1, struct coord *pos2, struct coord *pos3, struct coord *result);
void chopper_fire_rocket(struct chopperobj *chopper, bool side);
void chopper_increment_barrel(struct prop *prop, bool firing);
void chopper_increment_movement(struct prop *prop, f32 goalroty, f32 goalrotx, struct coord *dir, bool firing);
void chopper_tick_fall(struct prop *chopper);
void chopper_tick_idle(struct prop *chopper);
void chopper_tick_patrol(struct prop *chopper);
void chopper_tick_combat(struct prop *chopper);
void hovercar_tick(struct prop *hovercar);
void hoverprop_tick(struct prop *hoverprop, bool arg1);
void hoverbike_tick(struct prop *hoverbike, bool arg1);
void dropship_update_interior(struct prop *prop);
void glass_update_portal(struct prop *glass, s32 playercount, bool *arg2);
void weapon_init_matrices(struct prop *weapon);
void hangingmonitor_init_matrices(struct prop *hangingmonitors);
void obj_init_matrices(struct prop *prop);
bool prop_can_regen(struct prop *prop);
u32 obj_tick(struct prop *prop);
s32 obj_tick_player(struct prop *prop);
Gfx *props_render_beams(Gfx *gdl);
void tvscreen_set_cmdlist(struct tvscreen *screen, u32 *cmdlist);
void tvscreen_set_image_by_num(struct tvscreen *screen, s32 imagenum);
void tvscreen_set_texture(struct tvscreen *screen, s32 texturenum);
Gfx *tvscreen_render(struct model *model, struct modelnode *node, struct tvscreen *screen, Gfx *gdl, s32 arg4, s32 arg5);
void obj_render_prop(struct prop *prop, struct modelrenderdata *renderdata, bool xlupass);
Gfx *gfx_render_radial_shadow(Gfx *gdl, f32 x, f32 y, f32 z, f32 angle, f32 radius, u32 colour);
Gfx *obj_render_shadow(struct defaultobj *obj, Gfx *gdl);
Gfx *obj_render(struct prop *prop, Gfx *gdl, bool xlupass);
bool model_is_node_not_tvscreen(struct modeldef *modeldef, struct modelnode *node);
void obj_deform(struct defaultobj *obj, s32 level);
void obj_bounce(struct defaultobj *obj, struct coord *gundir2d);
void obj_set_dropped(struct prop *prop, u32 droptype);
void obj_apply_momentum(struct defaultobj *obj, struct coord *speed, f32 rotation, bool addspeed, bool addrotation);
void piracy_restore(void);
void func0f082e84(struct defaultobj *obj, struct coord *pos, struct coord *dir, struct coord *tween, bool addrotation);
void obj_detach(struct prop *prop);
bool obj_drop(struct prop *prop, bool lazy);
void obj_fall(struct defaultobj *obj, s32 playernum);
void obj_destroy_supported_objects(struct prop *prop, s32 playernum);
void obj_check_destroyed(struct defaultobj *obj, struct coord *pos, s32 playernum);
bool func0f084594(struct model *model, struct modelnode *node, struct coord *arg2, struct coord *arg3, struct hitthing *arg4, s32 *arg5, struct modelnode **arg6);
bool func0f0849dc(struct model *model, struct modelnode *nodearg, struct coord *arg2, struct coord *arg3, struct hitthing *hitthing, s32 *dstmtxindex, struct modelnode **dstnode);
u32 add43214321(u32 value);
void glass_destroy(struct defaultobj *obj);
void door_destroy_glass(struct doorobj *door);
void cctv_handle_lens_shot(struct defaultobj *obj);
void func0f085050(struct prop *prop, f32 damage, struct coord *pos, s32 arg3, s32 playernum);
bool func0f085194(struct defaultobj *obj);
bool obj_is_mortal(struct defaultobj *obj);
void obj_take_gunfire(struct defaultobj *obj, f32 damage, struct coord *pos, s32 weaponnum, s32 playernum);
void obj_damage(struct defaultobj *obj, f32 damage, struct coord *pos, s32 weaponnum, s32 playernum);
void func0f0859a0(struct prop *prop, struct shotdata *shotdata);
void obj_test_hit(struct prop *prop, struct shotdata *shotdata);
void obj_hit(struct shotdata *shotdata, struct hit *hit);
u32 propobj_get_ci_tag_id(struct prop *prop);
bool obj_is_healthy(struct defaultobj *obj);
bool obj_test_for_interact(struct prop *prop);
bool current_player_try_mount_hoverbike(struct prop *prop);
bool propobj_interact(struct prop *prop);
void obj_set_perim_enabled(struct prop *prop, bool enable);
bool obj_update_geometry(struct prop *prop, u8 **start, u8 **end);
void obj_get_bbox(struct prop *prop, f32 *radius, f32 *ymax, f32 *ymin);
void ammotype_get_picked_up_text(char *dst);
void ammotype_get_determiner(char *dst, s32 ammotype, s32 qty);
void ammotype_get_pickup_name(char *dst, s32 ammotype, s32 qty);
void ammotype_play_pickup_sound(u32 ammotype);
s32 prop_play_pickup_sound(struct prop *prop, s32 weapon);
void weapon_play_pickup_sound(s32 weaponnum);
void ammotype_get_pickup_message(char *dst, s32 ammotype, s32 qty);
void current_player_queue_pickup_ammo_hudmsg(s32 ammotype, s32 pickupqty);
void ammo_handle_pickup(s32 ammotype, s32 quantity, bool withsound, bool withhudmsg);
s32 ammocrate_get_pickup_ammo_qty(struct ammocrateobj *crate);
s32 weapon_get_pickup_ammo_qty(struct weaponobj *weapon);
void weapon_get_pickup_text(char *buffer, s32 weaponnum, bool dual);
void current_player_queue_pickup_weapon_hudmsg(u32 weaponnum, bool dual);
s32 prop_pickup_by_player(struct prop *prop, bool showhudmsg);
s32 obj_test_for_pickup(struct prop *prop);
bool func0f0899dc(struct prop *prop, struct coord *arg1, f32 *xrange, f32 *yrange);
void model_free_vertices(s32 vtxstoretype, struct model *model);
struct prop *hat_apply_to_chr(struct hatobj *hat, struct chrdata *chr, struct modeldef *modeldef, struct prop *prop, struct model *model);
void hat_load_and_apply_to_chr(struct hatobj *hat, struct chrdata *chr);
void hat_assign_to_chr(struct hatobj *hat, struct chrdata *chr);
struct prop *hat_create_for_chr(struct chrdata *chr, s32 modelnum, u32 flags);
struct weaponobj *weapon_create(bool musthaveprop, bool musthavemodel, struct modeldef *modeldef);
struct hatobj *hat_create(bool musthaveprop, bool musthavemodel, struct modeldef *modeldef);
struct ammocrateobj *ammocrate_allocate(void);
struct defaultobj *debris_allocate(void);
void player_activate_remote_mine_detonator(s32 playernum);
struct weaponobj *weapon_find_child_by_weapon_num(s32 weaponnum, struct prop *prop);
struct weaponobj *weapon_find_landed(s32 weaponnum);
void weapon_register_proxy(struct weaponobj *weapon);
void weapon_unregister_proxy(struct weaponobj *weapon);
void coord_trigger_proxies(struct coord *pos, bool arg1);
void chrs_trigger_proxies(void);
void propweapon_set_dual(struct weaponobj *weapon1, struct weaponobj *weapon2);
struct prop *func0f08adc8(struct weaponobj *weapon, struct modeldef *modeldef, struct prop *prop, struct model *model);
struct prop *func0f08ae0c(struct weaponobj *weapon, struct modeldef *modeldef);
bool chr_equip_weapon(struct weaponobj *weapon, struct chrdata *chr);
struct prop *func0f08b108(struct weaponobj *weapon, struct chrdata *chr, struct modeldef *modeldef, struct prop *prop, struct model *model);
void func0f08b208(struct weaponobj *weapon, struct chrdata *chr);
void func0f08b25c(struct weaponobj *weapon, struct chrdata *chr);
struct autogunobj *laptop_deploy(s32 modelnum, struct gset *gset, struct chrdata *chr);
struct weaponobj *weapon_create_projectile_from_gset(s32 modelnum, struct gset *gset, struct chrdata *chr);
struct weaponobj *weapon_create_projectile_from_weapon_num(s32 modelnum, s32 weaponnum, struct chrdata *chr);
void weapon_delete_from_chr(struct chrdata *chr, s32 hand);
struct prop *weapon_create_for_chr(struct chrdata *chr, s32 modelnum, s32 weaponnum, u32 flags, struct weaponobj *obj, struct modeldef *modeldef);
struct prop *chr_give_weapon(struct chrdata *chr, s32 model, s32 weaponnum, u32 flags);
s32 weapon_test_for_pickup(struct prop *prop);
void weapon_set_gunfire_visible(struct prop *prop, bool visible, RoomNum room);
bool weapon_is_gunfire_visible(struct prop *prop);
s32 hat_get_type(struct prop *prop);
bool door_is_unlocked(struct prop *playerprop, struct prop *doorprop);
bool door_is_pos_in_range(struct doorobj *door, struct coord *pos, f32 arg2, bool isbike);
bool door_is_obj_in_range(struct doorobj *door, struct defaultobj *obj, bool isbike);
bool vector_is_in_front_of_door(struct doorobj *door, struct coord *vector);
bool door_is_range_empty(struct doorobj *door);
void doors_check_automatic(void);
void func0f08c424(struct doorobj *door, Mtxf *matrix);
void door_get_bbox(struct doorobj *door, struct modelrodata_bbox *dst);
void door_update_tiles(struct doorobj *door);
void door0f08cb20(struct doorobj *door, Vtx *src, Vtx *dst, s32 numvertices);
void func0f08d3dc(struct doorobj *door);
void func0f08d460(struct doorobj *door);
void door_activate_portal(struct doorobj *door);
void door_deactivate_portal(struct doorobj *door);
struct prop *door_init(struct doorobj *door, struct coord *pos, Mtxf *mtx, RoomNum *rooms, struct coord *coord, struct coord *centre);
void door_play_opening_sound(s32 soundtype, struct prop *prop);
void door_play_closing_sound(s32 soundtype, struct prop *prop);
void door_play_opened_sound(s32 soundtype, struct prop *prop);
void door_play_closed_sound(s32 soundtype, struct prop *prop);
void door_start_open(struct doorobj *door);
void door_start_close(struct doorobj *door);
u32 decode_xor_aaaaaaaa(u32 value);
void door_finish_open(struct doorobj *door);
void door_finish_close(struct doorobj *door);
void door_set_mode(struct doorobj *door, s32 newmode);
void doors_request_mode(struct doorobj *door, s32 newmode);
s32 door_is_closed(struct doorobj *door);
s32 door_is_open(struct doorobj *door);
s32 func0f08e5a8(RoomNum *rooms, struct screenbox *box);
f32 obj_calculate_fade_dist_opacity_frac(struct prop *prop, f32 modelscale);
bool pos_is_in_obj_fade_distance(struct coord *coord, f32 modelscale);
bool func0f08e8ac(struct prop *prop, struct coord *pos, f32 arg2, bool arg3);
bool pos_is_in_draw_distance(struct coord *arg);
void door_create_sparks(struct doorobj *door);
bool door_calc_intended_frac(struct doorobj *door);
void doors_calc_frac(struct doorobj *door);
f32 func0f08f538(f32 x, f32 y);
void door0f08f604(struct doorobj *door, f32 *arg1, f32 *arg2, f32 *arg3, f32 *arg4, bool altcoordsystem);
bool func0f08f968(struct doorobj *door, bool altcoordsystem);
bool door_test_for_interact(struct prop *prop);
void doors_activate(struct prop *prop, bool allowliftclose);
bool pos_is_in_front_of_door(struct coord *pos, struct doorobj *door);
void doors_choose_swing_direction(struct prop *chrprop, struct doorobj *door);
bool propdoor_interact(struct prop *doorprop);
void alarm_stop_audio(void);
void gas_release_from_pos(struct coord *pos);
void gas_stop_audio(void);
bool gas_is_active(void);
void gas_tick(void);
Gfx *countdown_timer_render(Gfx *gdl);
void projectiles_debug(void);
void alarm_tick(void);
void func0f091030(void);
void current_player_drop_all_items(void);
void weapon_create_for_player_drop(s32 weaponnum);
void projectile_create(struct prop *fromprop, struct fireslotthing *arg1, struct coord *pos, struct coord *direction, u8 weaponnum, struct prop *targetprop);
void obj_set_model_part_visible(struct defaultobj *obj, s32 partnum, bool visible);

#endif
