#!/usr/bin/env python3

"""
This file defines which sequences are available and their sequence numbers
(based on their position in the array). The order should match the MUSIC
constants in constants.h.

This file is read by the tools/mksequences tool.
"""

sequences = [
    'dummy.seq',                   # 000
    'title-part1.seq',             # 001
    'extraction-pri.seq',          # 002
    'pause.seq',                   # 003
    'defense-pri.seq',             # 004
    'investigation-amb.seq',       # 005
    'escape-pri.seq',              # 006
    'deepsea-pri.seq',             # 007
    'defection-amb.seq',           # 008
    'defection-pri.seq',           # 009
    'solodeath.seq',               # 010
    'defection-intro-effects.seq', # 011
    'villa-pri.seq',               # 012
    'training-pri.seq',            # 013
    'chicago-pri.seq',             # 014
    'g5building-pri.seq',          # 015
    'defection-nrg.seq',           # 016
    'extraction-nrg.seq',          # 017
    'investigation-pri.seq',       # 018
    'investigation-nrg.seq',       # 019
    'infiltration-pri.seq',        # 020
    'mpdeath-beta.seq',            # 021
    'rescue-pri.seq',              # 022
    'airbase-pri.seq',             # 023
    'afo-pri.seq',                 # 024
    'mpdeath.seq',                 # 025
    'villa-intro.seq',             # 026
    'endscreen-missing.seq',       # 027
    'pelagic-pri.seq',             # 028
    'crashsite-pri.seq',           # 029
    'crashsite-nrg.seq',           # 030
    'attackship-pri.seq',          # 031
    'attackship-nrg.seq',          # 032
    'skedarruins-pri.seq',         # 033
    'defection-intro.seq',         # 034
    'defection-outro.seq',         # 035
    'defense-nrg.seq',             # 036
    'investigation-intro.seq',     # 037
    'investigation-outro.seq',     # 038
    'villa-nrg.seq',               # 039
    'chicago-nrg.seq',             # 040
    'g5building-nrg.seq',          # 041
    'infiltration-nrg.seq',        # 042
    'chicago-outro.seq',           # 043
    'extraction-outro.seq',        # 044
    'extraction-intro.seq',        # 045
    'g5building-intro.seq',        # 046
    'chicago-intro.seq',           # 047
    'villa-intro-v1.seq',          # 048
    'infiltration-intro.seq',      # 049
    'rescue-nrg.seq',              # 050
    'escape-nrg.seq',              # 051
    'airbase-nrg.seq',             # 052
    'afo-nrg.seq',                 # 053
    'pelagic-nrg.seq',             # 054
    'deepsea-nrg.seq',             # 055
    'skedarruins-nrg.seq',         # 056
    'airbase-intro-part2.seq',     # 057
    'darkcombat.seq',              # 058
    'skedarmystery.seq',           # 059
    'crashsite-intro-amb.seq',     # 060
    'cioperative.seq',             # 061
    'datadyneaction.seq',          # 062
    'maiantears.seq',              # 063
    'alienconflict.seq',           # 064
    'escape-intro.seq',            # 065
    'rescue-outro.seq',            # 066
    'villa-intro-v2.seq',          # 067
    'villa-intro-v3.seq',          # 068
    'g5building-outro.seq',        # 069
    'g5building-special.seq',      # 070
    'endscreen-failed.seq',        # 071
    'mpsetup.seq',                 # 072
    'endscreen-completed.seq',     # 073
    'crashsite-intro.seq',         # 074
    'airbase-intro.seq',           # 075
    'attackship-intro.seq',        # 076
    'deepsea-special.seq',         # 077
    'afo-intro.seq',               # 078
    'attackship-outro.seq',        # 079
    'escape-specical.seq',         # 080
    'rescue-intro.seq',            # 081
    'deepsea-intro.seq',           # 082
    'infiltration-outro.seq',      # 083
    'pelagic-intro.seq',           # 084
    'escape-outro-long.seq',       # 085
    'defense-intro.seq',           # 086
    'crashsite-outro.seq',         # 087
    'credits.seq',                 # 088
    'mainmenu.seq',                # 089
    'deepsea-outro.seq',           # 090
    'afo-special.seq',             # 091
    'pelagic-outro.seq',           # 092
    'afo-outro.seq',               # 093
    'skedarruins-intro.seq',       # 094
    'bloop.seq',                   # 095
    'airbase-outro.seq',           # 096
    'defense-outro.seq',           # 097
    'skedarruins-outro.seq',       # 098
    'villa-outro.seq',             # 099
    'skedarruins-king.seq',        # 100
    'training-session.seq',        # 101
    'crashsite-amb.seq',           # 102
    'mpendscreen-completed.seq',   # 103
    'ocean.seq',                   # 104
    'airbase-wind.seq',            # 105
    'chicago-traffic.seq',         # 106
    'title-part2.seq',             # 107
    'training-intro.seq',          # 108
    'infiltration-amb.seq',        # 109
    'deepsea-amb.seq',             # 110
    'afo-amb.seq',                 # 111
    'attackship-amb.seq',          # 112
    'skedarruins-amb.seq',         # 113
    'escape-outro-ufo.seq',        # 114
    'rescue-amb.seq',              # 115
    'escape-amb.seq',              # 116
    'jingle.seq',                  # 117
    'escape-outro-short.seq',      # 118
]
