#include <ultra64.h>

char *lang[] = {
	/*  0*/ "|Hintergrund - \n\nDas Bombardement wurde nunmehr eingestellt. Es werden nun Teams, bestehend aus Maianischen Protektoren, zusammengestellt, um die Oberfläche des Planeten zu durchkämmen. Ein spektrales Gen-Scanning hat ergeben, das ein neuer Anwärter auf den Thron der Skedar existiert.\n\n|1. Ziel: - Königsmord Teil Eins\n\nAls Joanna Dark den König der Skedar eliminierte, wurde sein Klon aktiviert. Der Klon müsste in seinem momentanen Stadium sehr desorientiert sein. Daher dürfte er nicht die gleiche Bedrohung darstellen, wie sein Vorgänger. Sie müssen ihn besiegen, bevor er die Kontrolle über die verbleibenden Soldaten der Skedar-Armee erlangt!\n\n|2. Ziel: - Königsmord Teil Zwei\n\nEs gibt noch einen zweiten Klon! Ein Fehler im System der Klon-Behälter hat dazu geführt, dass zwei Könige gleichzeitig aktiviert worden sind. Dieser Klon hatte mehr Zeit, sich zu akklimatisieren. Das bedeutet, dass er um ein Vielfaches gefährlicher ist. Wird er eliminiert, ist die Bedrohung vorüber.\n\n|3. Ziel: - Königsmord Teil Drei\n\nEs tut uns leid, aber es sieht so aus, als gäbe es noch einen dritten König. Aufgrund der starken Interferenzen nach dem Bombardement, konnten ihn unsere Scanner nicht erfassen. Dieser König konnte sich noch weiter entwickeln, als die beiden anderen. Das bedeutet, dass er noch gefährlicher ist. Die Notwendigkeit, ihn zu eliminieren, ist daher noch größer.\n\nENDE\n",
	/*  1*/ "KRIEGSSCHREIN\n",
	/*  2*/ "|Hintergrund - \n\nDas Bombardement wurde nunmehr eingestellt. Es werden nun Teams, bestehend aus Maianischen Protektoren, zusammengestellt, um die Oberfläche des Planeten zu durchkämmen. Ein spektrales Gen-Scanning hat ergeben, das ein neuer Anwärter auf den Thron der Skedar existiert.\n\n|1. Ziel: - Königsmord Teil Eins\n\nAls Joanna Dark den König der Skedar eliminierte, wurde sein Klon aktiviert. Der Klon müsste in seinem momentanen Stadium sehr desorientiert sein. Daher dürfte er nicht die gleiche Bedrohung darstellen, wie sein Vorgänger. Sie müssen ihn besiegen, bevor er die Kontrolle über die verbleibenden Soldaten der Skedar-Armee erlangt!\n\n|2. Ziel: - Königsmord Teil Zwei\n\nEs gibt noch einen zweiten Klon! Ein Fehler im System der Klon-Behälter hat dazu geführt, dass zwei Könige gleichzeitig aktiviert worden sind. Dieser Klon hatte mehr Zeit, sich zu akklimatisieren. Das bedeutet, dass er um ein Vielfaches gefährlicher ist. Wird er eliminiert, ist die Bedrohung vorüber.\n\nENDE\n",
	/*  3*/ "|Hintergrund - \n\nDas Bombardement wurde nunmehr eingestellt. Es werden nun Teams, bestehend aus Maianischen Protektoren, zusammengestellt, um die Oberfläche des Planeten zu durchkämmen. Ein spektrales Gen-Scanning hat ergeben, das ein neuer Anwärter auf den Thron der Skedar existiert.\n\n|1. Ziel: - Königsmord Teil Eins\n\nAls Joanna Dark den König der Skedar eliminierte, wurde sein Klon aktiviert. Der Klon müsste in seinem momentanen Stadium sehr desorientiert sein. Daher dürfte er nicht die gleiche Bedrohung darstellen, wie sein Vorgänger. Sie müssen ihn besiegen, bevor er die Kontrolle über die verbleibenden Soldaten der Skedar-Armee erlangt!\n\nENDE\n",
	/*  4*/ "Vernichten Sie den Skedar-König!\n",
	/*  5*/ "Vernichten Sie den Skedar-König 2!\n",
	/*  6*/ "Vernichten Sie den Skedar-König 3!\n",
	/*  7*/ "Der Maianische Anführer wurde eliminiert.\n",
	/*  8*/ "Der Skedar-König wurde eliminiert.\n",
	/*  9*/ NULL,
	/* 10*/ NULL,
	/* 11*/ NULL,
};
