#include <ultra64.h>

char *lang[] = {
	/*  0*/ "|Hintergrund - \n\nNotfall-Aufzeichnung aktiviert. Schiff XD-310372 wurde gezwungen, auf einem unerforschten Planeten notzulanden. Der einzige Überlebende ist der Maianische Protektor Nr. 1 (Aelphaeis Mangarae). Die Klassifizierung weist den Planeten als eine Welt im Prä-Kontakt-Status aus. Paranoia Grad 'B+', Intoleranz Grad 'B', Xenophobie Grad 'A'. Zerstören Sie die verbleibenden Ausrüstungsgegenstände, und verhindern Sie die Bergung von Maianischer Technologie und/oder Personal.\n\n|1. Ziel: - Sabotieren Sie das gegnerische medizinische Experiment!\n\nBei der Person, für die ich verantwortlich war, handelte es sich um den Maianischen Botschafter. Derzeit sollen an seinem Körper Experimente durchgeführt werden. Um meine Pflicht als Maianischer Protektor zu erfüllen, muss ich dafür Sorge tragen, dass der Körper zerstört wird.\n\n|2. Ziel: - Zerstören Sie das Maianische Schiff!\n\nMein letzter Akt der Pflichterfüllung besteht darin, das Schiff, mit dem ich die Erde erreicht habe, zu zerstören. Sollte irgendjemand feststellen, dass die sich an Bord befindliche Technologie der des Carrington Instituts ähnlich ist, geraten unsere Verbündeten auf der Erde in Gefahr, und meine Mission ist gescheitert.\n\n|3. Ziel: - Senden Sie ein Notsignal an Ihre Verbündeten!\n\nDas Carrington Institut kann mir eventuell helfen. Wenn es mir gelingt, eine Nachricht an sie zu schicken, können sie meine Position feststellen. Um die technische Ausrüstung, die ich nicht finde, wird sich dann das Institut kümmern.\n\nENDE\n",
	/*  1*/ "AREA 51, NEVADA, ERDE\n",
	/*  2*/ "|Hintergrund - \n\nNotfall-Aufzeichnung aktiviert. Schiff XD-310372 wurde gezwungen, auf einem unerforschten Planeten notzulanden. Der einzige Überlebende ist der Maianische Protektor Nr. 1 (Aelphaeis Mangarae). Die Klassifizierung weist den Planeten als eine Welt im Prä-Kontakt-Status aus. Paranoia Grad 'B+', Intoleranz Grad 'B', Xenophobie Grad 'A'. Zerstören Sie die verbleibenden Ausrüstungsgegenstände, und verhindern Sie die Bergung von Maianischer Technologie und/oder Personal.\n\n|1. Ziel: - Sabotieren Sie das gegnerische medizinische Experiment!\n\nBei der Person, für die ich verantwortlich war, handelte es sich um den Maianischen Botschafter. Derzeit sollen an seinem Körper Experimente durchgeführt werden. Um meine Pflicht als Maianischer Protektor zu erfüllen, muss ich dafür Sorge tragen, dass der Körper zerstört wird.\n\n|2. Ziel: - Senden Sie ein Notsignal an Ihre Verbündeten!\n\nDas Carrington Institut kann mir eventuell helfen. Wenn es mir gelingt, eine Nachricht an sie zu schicken, können sie meine Position feststellen. Um die technische Ausrüstung, die ich nicht finde, wird sich dann das Institut kümmern.\n\nENDE\n",
	/*  3*/ "|Hintergrund - \n\nNotfall-Aufzeichnung aktiviert. Schiff XD-310372 wurde gezwungen, auf einem unerforschten Planeten notzulanden. Der einzige Überlebende ist der Maianische Protektor Nr. 1 (Aelphaeis Mangarae). Die Klassifizierung weist den Planeten als eine Welt im Prä-Kontakt-Status aus. Paranoia Grad 'B+', Intoleranz Grad 'B', Xenophobie Grad 'A'. Zerstören Sie die verbleibenden Ausrüstungsgegenstände, und verhindern Sie die Bergung von Maianischer Technologie und/oder Personal.\n\n|1. Ziel: - Senden Sie ein Notsignal an Ihre Verbündeten!\n\nDas Carrington Institut kann mir eventuell helfen. Wenn es mir gelingt, eine Nachricht an sie zu schicken, können sie meine Position feststellen. Um die technische Ausrüstung, die ich nicht finde, wird sich dann das Institut kümmern.\n\nENDE\n",
	/*  4*/ "Sabotieren Sie das Experiment!\n",
	/*  5*/ "Zerstören Sie das Maianische Schiff!\n",
	/*  6*/ "Senden Sie ein Notsignal!\n",
	/*  7*/ "Medizinisches Experiment wurde sabotiert.\n",
	/*  8*/ "Das Maianische Schiff wurde zerstört.\n",
	/*  9*/ "Notsignal wurde gesendet.\n",
	/* 10*/ "Wichtiges Objekt wurde zerstört.\n",
	/* 11*/ "MISSION FEHLGESCHLAGEN - Flucht ist nicht mehr möglich.\n",
	/* 12*/ "Es wurde eine alternative Fluchtroute gefunden.\n",
	/* 13*/ NULL,
	/* 14*/ NULL,
	/* 15*/ NULL,
};
